if (!("Brotherhood" in getroottable())) return;

// Fixed simulator snapshots generated by tools/sync_parent_runtime_data.py.
// Screens and ForcedAnchorID are explicit so parity does not depend on matching
// Python's blake2b-seeded Random with Squirrel's Park-Miller career stream.
::Brotherhood.ParentParityFixtures <- [
	{
		ID="ordinary_melee_1", Category="ordinary_melee",
		ForcedAnchorID="tank_banner",
		Body={
			Seed=1006595446796710652, RecruitUID=1006595446796710652, RecruitName="Parity ordinary_melee_1",
			BackgroundID="background.manual", BackgroundName="Orc Slayer",
			TraitIDs=["trait.deathwish"], TraitNames=["Deathwish"],
			Stats={ hitpoints_max=70.0, resolve=50.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=3.0, ranged_defense=3.0, initiative=109.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=3, melee_skill=0, ranged_skill=1, melee_defense=0, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=2, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[4, 2, 5, 4, 3, 3, 1, 4] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 5, 5, 2, 3, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 5, 3, 3, 3, 2, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 4, 2, 4, 2, 3] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=4, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 5, 4, 1, 3, 2, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=5, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 3, 5, 4, 2, 4, 1, 3] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 5, 4, 3, 3, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 5, 2, 3, 2, 3] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=3}, Ordered=[3, 3, 5, 5, 3, 3, 1, 3] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 4, 5, 3, 4, 3, 4] }
		],
		Expected={
			Recognized=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank_banner",
			SharedFuture={ hitpoints_max=103.0, resolve=82.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=23.0, ranged_defense=3.0, initiative=109.0 },
			SecondaryQualified=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank"],
			Selected=["tank_banner", "tank", "fatigue_carry", "attack_banner"]
		}
	},
	{
		ID="ordinary_melee_2", Category="ordinary_melee",
		ForcedAnchorID="qatal_duelist",
		Body={
			Seed=7315402712511117733, RecruitUID=7315402712511117733, RecruitName="Parity ordinary_melee_2",
			BackgroundID="background.manual", BackgroundName="Pimp",
			TraitIDs=["trait.survivor"], TraitNames=["Survivor"],
			Stats={ hitpoints_max=59.0, resolve=37.0, fatigue=97.0, melee_skill=45.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=9.0, initiative=117.0 }, Stars={ hitpoints_max=0, resolve=2, fatigue=0, melee_skill=2, ranged_skill=0, melee_defense=0, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 2, 5, 3, 4, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=2, melee_defense=1, ranged_defense=2}, Ordered=[2, 4, 4, 4, 3, 2, 1, 2] },
			{ Level=4, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[2, 4, 3, 5, 3, 3, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 4, 3, 5, 3, 3, 1, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 5, 3, 2, 2, 3] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 3, 3, 3, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 5, 3, 3, 2, 3] },
			{ Level=9, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 4, 4, 3, 3, 3, 1, 4] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=2}, Ordered=[3, 4, 4, 4, 3, 3, 1, 2] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 4, 4, 3, 3, 4, 1, 3] }
		],
		Expected={
			Recognized=["archer", "qatal_duelist", "reload_ranged"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "tank", "tank_banner"],
			Anchor="qatal_duelist",
			SharedFuture={ hitpoints_max=59.0, resolve=37.0, fatigue=97.0, melee_skill=75.0, ranged_skill=39.0, melee_defense=22.0, ranged_defense=9.0, initiative=159.0 },
			SecondaryQualified=["archer", "reload_ranged"],
			Selected=["qatal_duelist", "reload_ranged", "archer", "tempo"]
		}
	},
	{
		ID="ordinary_melee_3", Category="ordinary_melee",
		ForcedAnchorID="tank",
		Body={
			Seed=7107360525417620049, RecruitUID=7107360525417620049, RecruitName="Parity ordinary_melee_3",
			BackgroundID="background.manual", BackgroundName="Deserter",
			TraitIDs=["trait.fear of beasts", "trait.hate for undead"], TraitNames=["Fear of Beasts", "Hate for Undead"],
			Stats={ hitpoints_max=53.0, resolve=27.0, fatigue=97.0, melee_skill=61.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=5.0, initiative=110.0 }, Stars={ hitpoints_max=2, resolve=1, fatigue=0, melee_skill=0, ranged_skill=0, melee_defense=2, ranged_defense=0, initiative=2 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 3, 2, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 3, 3, 3, 4] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 1, 4, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 1, 3, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 3, 4, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 2, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 1, 4, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 3, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=1, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 1, 2, 3, 4] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 2, 4, 3, 3] }
		],
		Expected={
			Recognized=["archer", "duelist", "hybrid", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank",
			SharedFuture={ hitpoints_max=93.0, resolve=54.0, fatigue=104.0, melee_skill=61.0, ranged_skill=39.0, melee_defense=35.0, ranged_defense=5.0, initiative=110.0 },
			SecondaryQualified=["archer", "duelist", "fatigue_carry", "qatal_duelist", "reload_ranged", "support_frontliner", "tank_banner"],
			Selected=["tank", "tank_banner", "fatigue_carry", "duelist"]
		}
	},
	{
		ID="ordinary_ranged_1", Category="ordinary_ranged",
		ForcedAnchorID="pure_thrower",
		Body={
			Seed=17728450145152037944, RecruitUID=17728450145152037944, RecruitName="Parity ordinary_ranged_1",
			BackgroundID="background.manual", BackgroundName="Messenger",
			TraitIDs=[], TraitNames=[],
			Stats={ hitpoints_max=56.0, resolve=36.0, fatigue=105.0, melee_skill=53.0, ranged_skill=41.0, melee_defense=4.0, ranged_defense=8.0, initiative=100.0 }, Stars={ hitpoints_max=0, resolve=3, fatigue=0, melee_skill=1, ranged_skill=0, melee_defense=1, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=2, resolve=5, fatigue=3, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[2, 5, 3, 5, 2, 3, 2, 4] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 5, 4, 5, 3, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 2, 5, 2, 2, 2, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=5, fatigue=4, initiative=4, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=3}, Ordered=[4, 5, 4, 4, 2, 2, 3, 3] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 3, 3, 2, 4, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=2, resolve=5, fatigue=4, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[2, 5, 4, 5, 3, 3, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=5, fatigue=2, initiative=3, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 5, 2, 3, 3, 2, 3, 4] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=5, fatigue=3, initiative=3, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 5, 3, 3, 2, 3, 3, 3] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=5, fatigue=3, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[4, 5, 3, 4, 2, 4, 2, 3] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=3}, Ordered=[3, 5, 4, 5, 2, 2, 3, 3] }
		],
		Expected={
			Recognized=["attack_banner", "hybrid", "pure_thrower", "tank_banner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="pure_thrower",
			SharedFuture={ hitpoints_max=56.0, resolve=36.0, fatigue=137.0, melee_skill=53.0, ranged_skill=70.0, melee_defense=4.0, ranged_defense=42.0, initiative=100.0 },
			SecondaryQualified=["archer", "attack_banner", "duelist", "fatigue_carry", "reload_ranged", "tank", "tank_banner"],
			Selected=["pure_thrower", "reload_ranged", "tank", "archer"]
		}
	},
	{
		ID="ordinary_ranged_2", Category="ordinary_ranged",
		ForcedAnchorID="qatal_duelist",
		Body={
			Seed=7315402712511117733, RecruitUID=7315402712511117733, RecruitName="Parity ordinary_ranged_2",
			BackgroundID="background.manual", BackgroundName="Pimp",
			TraitIDs=["trait.survivor"], TraitNames=["Survivor"],
			Stats={ hitpoints_max=59.0, resolve=37.0, fatigue=97.0, melee_skill=45.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=9.0, initiative=117.0 }, Stars={ hitpoints_max=0, resolve=2, fatigue=0, melee_skill=2, ranged_skill=0, melee_defense=0, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 2, 5, 3, 4, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=2, melee_defense=1, ranged_defense=2}, Ordered=[2, 4, 4, 4, 3, 2, 1, 2] },
			{ Level=4, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[2, 4, 3, 5, 3, 3, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 4, 3, 5, 3, 3, 1, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 5, 3, 2, 2, 3] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 3, 3, 3, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 5, 3, 3, 2, 3] },
			{ Level=9, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 4, 4, 3, 3, 3, 1, 4] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=2}, Ordered=[3, 4, 4, 4, 3, 3, 1, 2] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 4, 4, 3, 3, 4, 1, 3] }
		],
		Expected={
			Recognized=["archer", "qatal_duelist", "reload_ranged"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "tank", "tank_banner"],
			Anchor="qatal_duelist",
			SharedFuture={ hitpoints_max=59.0, resolve=37.0, fatigue=97.0, melee_skill=75.0, ranged_skill=39.0, melee_defense=22.0, ranged_defense=9.0, initiative=159.0 },
			SecondaryQualified=["archer", "reload_ranged"],
			Selected=["qatal_duelist", "reload_ranged", "archer", "tempo"]
		}
	},
	{
		ID="ordinary_ranged_3", Category="ordinary_ranged",
		ForcedAnchorID="archer",
		Body={
			Seed=9411545128604104708, RecruitUID=9411545128604104708, RecruitName="Parity ordinary_ranged_3",
			BackgroundID="background.manual", BackgroundName="Lindwurm Slayer",
			TraitIDs=["trait.brave", "trait.short sighted"], TraitNames=["Brave", "Short Sighted"],
			Stats={ hitpoints_max=56.0, resolve=47.0, fatigue=104.0, melee_skill=59.0, ranged_skill=47.0, melee_defense=6.0, ranged_defense=-1.0, initiative=116.0 }, Stars={ hitpoints_max=0, resolve=0, fatigue=2, melee_skill=1, ranged_skill=0, melee_defense=0, ranged_defense=2, initiative=2 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 2, 4, 5, 3, 2, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=4}, Ordered=[4, 4, 4, 5, 2, 4, 1, 4] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 4, 5, 3, 4, 2, 4] },
			{ Level=5, Rolls={hitpoints_max=2, resolve=3, fatigue=4, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[2, 3, 4, 5, 3, 3, 2, 4] },
			{ Level=6, Rolls={hitpoints_max=2, resolve=2, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 2, 4, 5, 2, 3, 1, 4] },
			{ Level=7, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[3, 3, 4, 5, 3, 3, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=2, resolve=2, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[2, 2, 4, 5, 2, 4, 2, 4] },
			{ Level=9, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[2, 4, 4, 5, 2, 2, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[4, 4, 4, 5, 3, 4, 2, 4] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 2, 4, 5, 3, 4, 3, 4] }
		],
		Expected={
			Recognized=["archer", "attack_banner", "duelist", "fatigue_carry", "hybrid", "pure_thrower", "qatal_duelist", "reload_ranged", "tank"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="archer",
			SharedFuture={ hitpoints_max=56.0, resolve=47.0, fatigue=104.0, melee_skill=59.0, ranged_skill=80.0, melee_defense=6.0, ranged_defense=39.0, initiative=166.0 },
			SecondaryQualified=["attack_banner", "duelist", "fatigue_carry", "hybrid", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "tank"],
			Selected=["archer", "pure_thrower", "reload_ranged", "attack_banner"]
		}
	},
	{
		ID="defensive_1", Category="defensive",
		ForcedAnchorID="tank_banner",
		Body={
			Seed=1006595446796710652, RecruitUID=1006595446796710652, RecruitName="Parity defensive_1",
			BackgroundID="background.manual", BackgroundName="Orc Slayer",
			TraitIDs=["trait.deathwish"], TraitNames=["Deathwish"],
			Stats={ hitpoints_max=70.0, resolve=50.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=3.0, ranged_defense=3.0, initiative=109.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=3, melee_skill=0, ranged_skill=1, melee_defense=0, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=2, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[4, 2, 5, 4, 3, 3, 1, 4] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 5, 5, 2, 3, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 5, 3, 3, 3, 2, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 4, 2, 4, 2, 3] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=4, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 5, 4, 1, 3, 2, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=5, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 3, 5, 4, 2, 4, 1, 3] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 5, 4, 3, 3, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 5, 2, 3, 2, 3] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=3}, Ordered=[3, 3, 5, 5, 3, 3, 1, 3] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 4, 5, 3, 4, 3, 4] }
		],
		Expected={
			Recognized=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank_banner",
			SharedFuture={ hitpoints_max=103.0, resolve=82.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=23.0, ranged_defense=3.0, initiative=109.0 },
			SecondaryQualified=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank"],
			Selected=["tank_banner", "tank", "fatigue_carry", "attack_banner"]
		}
	},
	{
		ID="defensive_2", Category="defensive",
		ForcedAnchorID="pure_thrower",
		Body={
			Seed=17728450145152037944, RecruitUID=17728450145152037944, RecruitName="Parity defensive_2",
			BackgroundID="background.manual", BackgroundName="Messenger",
			TraitIDs=[], TraitNames=[],
			Stats={ hitpoints_max=56.0, resolve=36.0, fatigue=105.0, melee_skill=53.0, ranged_skill=41.0, melee_defense=4.0, ranged_defense=8.0, initiative=100.0 }, Stars={ hitpoints_max=0, resolve=3, fatigue=0, melee_skill=1, ranged_skill=0, melee_defense=1, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=2, resolve=5, fatigue=3, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[2, 5, 3, 5, 2, 3, 2, 4] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 5, 4, 5, 3, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 2, 5, 2, 2, 2, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=5, fatigue=4, initiative=4, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=3}, Ordered=[4, 5, 4, 4, 2, 2, 3, 3] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 3, 3, 2, 4, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=2, resolve=5, fatigue=4, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[2, 5, 4, 5, 3, 3, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=5, fatigue=2, initiative=3, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 5, 2, 3, 3, 2, 3, 4] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=5, fatigue=3, initiative=3, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 5, 3, 3, 2, 3, 3, 3] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=5, fatigue=3, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[4, 5, 3, 4, 2, 4, 2, 3] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=3}, Ordered=[3, 5, 4, 5, 2, 2, 3, 3] }
		],
		Expected={
			Recognized=["attack_banner", "hybrid", "pure_thrower", "tank_banner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="pure_thrower",
			SharedFuture={ hitpoints_max=56.0, resolve=36.0, fatigue=137.0, melee_skill=53.0, ranged_skill=70.0, melee_defense=4.0, ranged_defense=42.0, initiative=100.0 },
			SecondaryQualified=["archer", "attack_banner", "duelist", "fatigue_carry", "reload_ranged", "tank", "tank_banner"],
			Selected=["pure_thrower", "reload_ranged", "tank", "archer"]
		}
	},
	{
		ID="defensive_3", Category="defensive",
		ForcedAnchorID="tank",
		Body={
			Seed=7107360525417620049, RecruitUID=7107360525417620049, RecruitName="Parity defensive_3",
			BackgroundID="background.manual", BackgroundName="Deserter",
			TraitIDs=["trait.fear of beasts", "trait.hate for undead"], TraitNames=["Fear of Beasts", "Hate for Undead"],
			Stats={ hitpoints_max=53.0, resolve=27.0, fatigue=97.0, melee_skill=61.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=5.0, initiative=110.0 }, Stars={ hitpoints_max=2, resolve=1, fatigue=0, melee_skill=0, ranged_skill=0, melee_defense=2, ranged_defense=0, initiative=2 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 3, 2, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 3, 3, 3, 4] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 1, 4, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 1, 3, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 3, 4, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 2, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 1, 4, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 3, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=1, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 1, 2, 3, 4] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 2, 4, 3, 3] }
		],
		Expected={
			Recognized=["archer", "duelist", "hybrid", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank",
			SharedFuture={ hitpoints_max=93.0, resolve=54.0, fatigue=104.0, melee_skill=61.0, ranged_skill=39.0, melee_defense=35.0, ranged_defense=5.0, initiative=110.0 },
			SecondaryQualified=["archer", "duelist", "fatigue_carry", "qatal_duelist", "reload_ranged", "support_frontliner", "tank_banner"],
			Selected=["tank", "tank_banner", "fatigue_carry", "duelist"]
		}
	},
	{
		ID="banner_1", Category="banner",
		ForcedAnchorID="tank_banner",
		Body={
			Seed=1006595446796710652, RecruitUID=1006595446796710652, RecruitName="Parity banner_1",
			BackgroundID="background.manual", BackgroundName="Orc Slayer",
			TraitIDs=["trait.deathwish"], TraitNames=["Deathwish"],
			Stats={ hitpoints_max=70.0, resolve=50.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=3.0, ranged_defense=3.0, initiative=109.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=3, melee_skill=0, ranged_skill=1, melee_defense=0, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=2, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[4, 2, 5, 4, 3, 3, 1, 4] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 5, 5, 2, 3, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 5, 3, 3, 3, 2, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 4, 2, 4, 2, 3] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=4, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 5, 4, 1, 3, 2, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=5, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 3, 5, 4, 2, 4, 1, 3] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 5, 4, 3, 3, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 5, 2, 3, 2, 3] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=3}, Ordered=[3, 3, 5, 5, 3, 3, 1, 3] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 4, 5, 3, 4, 3, 4] }
		],
		Expected={
			Recognized=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank_banner",
			SharedFuture={ hitpoints_max=103.0, resolve=82.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=23.0, ranged_defense=3.0, initiative=109.0 },
			SecondaryQualified=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank"],
			Selected=["tank_banner", "tank", "fatigue_carry", "attack_banner"]
		}
	},
	{
		ID="banner_2", Category="banner",
		ForcedAnchorID="tank",
		Body={
			Seed=7107360525417620049, RecruitUID=7107360525417620049, RecruitName="Parity banner_2",
			BackgroundID="background.manual", BackgroundName="Deserter",
			TraitIDs=["trait.fear of beasts", "trait.hate for undead"], TraitNames=["Fear of Beasts", "Hate for Undead"],
			Stats={ hitpoints_max=53.0, resolve=27.0, fatigue=97.0, melee_skill=61.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=5.0, initiative=110.0 }, Stars={ hitpoints_max=2, resolve=1, fatigue=0, melee_skill=0, ranged_skill=0, melee_defense=2, ranged_defense=0, initiative=2 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 3, 2, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 3, 3, 3, 4] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 1, 4, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 5, 1, 3, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 3, 4, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 2, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 1, 4, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 3, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=1, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 1, 2, 3, 4] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 2, 4, 3, 3] }
		],
		Expected={
			Recognized=["archer", "duelist", "hybrid", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank",
			SharedFuture={ hitpoints_max=93.0, resolve=54.0, fatigue=104.0, melee_skill=61.0, ranged_skill=39.0, melee_defense=35.0, ranged_defense=5.0, initiative=110.0 },
			SecondaryQualified=["archer", "duelist", "fatigue_carry", "qatal_duelist", "reload_ranged", "support_frontliner", "tank_banner"],
			Selected=["tank", "tank_banner", "fatigue_carry", "duelist"]
		}
	},
	{
		ID="banner_3", Category="banner",
		ForcedAnchorID="support_frontliner",
		Body={
			Seed=15971576530312179416, RecruitUID=15971576530312179416, RecruitName="Parity banner_3",
			BackgroundID="background.manual", BackgroundName="Eunuch",
			TraitIDs=["trait.sure footing"], TraitNames=["Sure Footing"],
			Stats={ hitpoints_max=57.0, resolve=29.0, fatigue=95.0, melee_skill=55.0, ranged_skill=38.0, melee_defense=8.0, ranged_defense=3.0, initiative=104.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=0, melee_skill=1, ranged_skill=0, melee_defense=2, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=2, fatigue=2, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=2}, Ordered=[3, 2, 2, 5, 3, 2, 3, 2] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 4, 4, 3, 3, 3, 4] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 4, 4, 2, 4, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=4, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=2}, Ordered=[4, 2, 4, 4, 2, 2, 3, 2] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 3, 4, 2, 3, 3, 2] },
			{ Level=7, Rolls={hitpoints_max=3, resolve=2, fatigue=2, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=2}, Ordered=[3, 2, 2, 5, 2, 2, 3, 2] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 4, 5, 3, 4, 3, 2] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 3, 4, 2, 3, 3, 2] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 4, 3, 4, 3, 3] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 2, 4, 4, 3, 3, 3, 3] }
		],
		Expected={
			Recognized=["duelist", "fatigue_carry", "qatal_duelist", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="support_frontliner",
			SharedFuture={ hitpoints_max=92.0, resolve=29.0, fatigue=95.0, melee_skill=80.0, ranged_skill=38.0, melee_defense=38.0, ranged_defense=3.0, initiative=104.0 },
			SecondaryQualified=["duelist", "fatigue_carry", "qatal_duelist", "tank", "tank_banner"],
			Selected=["support_frontliner", "tank", "fatigue_carry", "tank_banner"]
		}
	},
	{
		ID="hybrid_legit_1", Category="hybrid_legit",
		ForcedAnchorID="hybrid",
		Body={
			Seed=2538010196208641704, RecruitUID=2538010196208641704, RecruitName="Parity hybrid_legit_1",
			BackgroundID="background.manual", BackgroundName="Slave",
			TraitIDs=["trait.fainthearted"], TraitNames=["Fainthearted"],
			Stats={ hitpoints_max=40.0, resolve=27.0, fatigue=88.0, melee_skill=64.0, ranged_skill=56.0, melee_defense=-9.0, ranged_defense=-3.0, initiative=116.0 }, Stars={ hitpoints_max=0, resolve=0, fatigue=0, melee_skill=1, ranged_skill=2, melee_defense=2, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=2, resolve=2, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[2, 2, 2, 5, 3, 4, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 3, 5, 2, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=2, resolve=3, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[2, 3, 4, 3, 3, 4, 3, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=2, fatigue=2, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 2, 2, 5, 2, 4, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 4, 3, 2, 4, 3, 3] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 3, 3, 3, 4, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=2, resolve=2, fatigue=3, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[2, 2, 3, 5, 2, 4, 3, 4] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=2, fatigue=2, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 2, 2, 3, 2, 4, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=2, resolve=2, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[2, 2, 2, 5, 3, 4, 3, 3] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=2, fatigue=3, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 2, 3, 3, 3, 4, 3, 4] }
		],
		Expected={
			Recognized=["archer", "attack_banner", "duelist", "fatigue_carry", "hybrid", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "hybrid", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank"],
			Anchor="hybrid",
			SharedFuture={ hitpoints_max=40.0, resolve=27.0, fatigue=88.0, melee_skill=89.0, ranged_skill=96.0, melee_defense=21.0, ranged_defense=-3.0, initiative=116.0 },
			SecondaryQualified=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner"],
			Selected=["hybrid", "support_frontliner", "injury_specialist", "archer"]
		}
	},
	{
		ID="hybrid_legit_2", Category="hybrid_legit",
		ForcedAnchorID="hybrid",
		Body={
			Seed=7044118353259006867, RecruitUID=7044118353259006867, RecruitName="Parity hybrid_legit_2",
			BackgroundID="background.manual", BackgroundName="Belly Dancer",
			TraitIDs=["trait.disloyal", "trait.impatient"], TraitNames=["Disloyal", "Impatient"],
			Stats={ hitpoints_max=52.0, resolve=29.0, fatigue=91.0, melee_skill=67.0, ranged_skill=46.0, melee_defense=3.0, ranged_defense=5.0, initiative=113.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=1, melee_skill=1, ranged_skill=2, melee_defense=0, ranged_defense=3, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=4}, Ordered=[4, 4, 4, 3, 2, 4, 1, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=5}, Ordered=[4, 4, 3, 4, 3, 4, 2, 5] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=2, fatigue=3, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[3, 2, 3, 5, 3, 4, 2, 4] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 4, 4, 3, 4, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=1, ranged_defense=4}, Ordered=[3, 4, 3, 3, 3, 4, 1, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=2, fatigue=3, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 2, 3, 3, 3, 4, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=5}, Ordered=[4, 2, 4, 3, 3, 4, 2, 5] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=5}, Ordered=[4, 2, 4, 3, 3, 4, 3, 5] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=2, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[3, 2, 4, 4, 2, 4, 2, 4] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=5}, Ordered=[4, 2, 4, 5, 2, 4, 2, 5] }
		],
		Expected={
			Recognized=["archer", "attack_banner", "duelist", "fatigue_carry", "hybrid", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "hybrid", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="hybrid",
			SharedFuture={ hitpoints_max=52.0, resolve=29.0, fatigue=91.0, melee_skill=94.0, ranged_skill=86.0, melee_defense=24.0, ranged_defense=5.0, initiative=113.0 },
			SecondaryQualified=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner"],
			Selected=["hybrid", "injury_specialist", "fatigue_carry", "qatal_duelist"]
		}
	},
	{
		ID="hybrid_legit_3", Category="hybrid_legit",
		ForcedAnchorID="injury_specialist",
		Body={
			Seed=15433990250853525423, RecruitUID=15433990250853525423, RecruitName="Parity hybrid_legit_3",
			BackgroundID="background.manual", BackgroundName="Servant",
			TraitIDs=["trait.asthmatic"], TraitNames=["Asthmatic"],
			Stats={ hitpoints_max=49.0, resolve=28.0, fatigue=89.0, melee_skill=57.0, ranged_skill=41.0, melee_defense=0.0, ranged_defense=4.0, initiative=106.0 }, Stars={ hitpoints_max=0, resolve=0, fatigue=2, melee_skill=0, ranged_skill=1, melee_defense=1, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=2, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[2, 3, 4, 4, 2, 3, 3, 2] },
			{ Level=3, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[2, 4, 4, 5, 1, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 4, 5, 1, 4, 3, 3] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 3, 4, 5, 2, 3, 2, 3] },
			{ Level=6, Rolls={hitpoints_max=2, resolve=3, fatigue=4, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[2, 3, 4, 3, 2, 4, 2, 4] },
			{ Level=7, Rolls={hitpoints_max=2, resolve=2, fatigue=4, initiative=3, melee_skill=1, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[2, 2, 4, 3, 1, 4, 2, 4] },
			{ Level=8, Rolls={hitpoints_max=2, resolve=3, fatigue=4, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[2, 3, 4, 4, 3, 4, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=2}, Ordered=[4, 4, 4, 3, 1, 3, 2, 2] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[4, 2, 4, 5, 1, 4, 2, 4] },
			{ Level=11, Rolls={hitpoints_max=2, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[2, 3, 4, 5, 2, 3, 3, 2] }
		],
		Expected={
			Recognized=["hybrid"],
			Reachable=["archer", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "tank"],
			Anchor="injury_specialist",
			SharedFuture={ hitpoints_max=76.0, resolve=28.0, fatigue=89.0, melee_skill=57.0, ranged_skill=77.0, melee_defense=25.0, ranged_defense=4.0, initiative=106.0 },
			SecondaryQualified=["archer", "hybrid", "pure_thrower", "reload_ranged"],
			Selected=["injury_specialist", "pure_thrower", "hybrid", "reload_ranged"]
		}
	},
	{
		ID="hybrid_narrow_fail_1", Category="hybrid_narrow_fail",
		ForcedAnchorID="tank_banner",
		Body={
			Seed=1006595446796710652, RecruitUID=1006595446796710652, RecruitName="Parity hybrid_narrow_fail_1",
			BackgroundID="background.manual", BackgroundName="Orc Slayer",
			TraitIDs=["trait.deathwish"], TraitNames=["Deathwish"],
			Stats={ hitpoints_max=70.0, resolve=50.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=3.0, ranged_defense=3.0, initiative=109.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=3, melee_skill=0, ranged_skill=1, melee_defense=0, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=2, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[4, 2, 5, 4, 3, 3, 1, 4] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 5, 5, 2, 3, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 5, 3, 3, 3, 2, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 4, 2, 4, 2, 3] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=5, initiative=4, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 5, 4, 1, 3, 2, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=3, fatigue=5, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 3, 5, 4, 2, 4, 1, 3] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 5, 4, 3, 3, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 5, 2, 3, 2, 3] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=3, fatigue=5, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=3}, Ordered=[3, 3, 5, 5, 3, 3, 1, 3] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 4, 5, 3, 4, 3, 4] }
		],
		Expected={
			Recognized=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="tank_banner",
			SharedFuture={ hitpoints_max=103.0, resolve=82.0, fatigue=107.0, melee_skill=67.0, ranged_skill=28.0, melee_defense=23.0, ranged_defense=3.0, initiative=109.0 },
			SecondaryQualified=["attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "support_frontliner", "tank"],
			Selected=["tank_banner", "tank", "fatigue_carry", "attack_banner"]
		}
	},
	{
		ID="hybrid_narrow_fail_2", Category="hybrid_narrow_fail",
		ForcedAnchorID="qatal_duelist",
		Body={
			Seed=7315402712511117733, RecruitUID=7315402712511117733, RecruitName="Parity hybrid_narrow_fail_2",
			BackgroundID="background.manual", BackgroundName="Pimp",
			TraitIDs=["trait.survivor"], TraitNames=["Survivor"],
			Stats={ hitpoints_max=59.0, resolve=37.0, fatigue=97.0, melee_skill=45.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=9.0, initiative=117.0 }, Stars={ hitpoints_max=0, resolve=2, fatigue=0, melee_skill=2, ranged_skill=0, melee_defense=0, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 2, 5, 3, 4, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=2, melee_defense=1, ranged_defense=2}, Ordered=[2, 4, 4, 4, 3, 2, 1, 2] },
			{ Level=4, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[2, 4, 3, 5, 3, 3, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 4, 3, 5, 3, 3, 1, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 5, 3, 2, 2, 3] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 3, 3, 3, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 3, 5, 3, 3, 2, 3] },
			{ Level=9, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=4}, Ordered=[2, 4, 4, 3, 3, 3, 1, 4] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=2}, Ordered=[3, 4, 4, 4, 3, 3, 1, 2] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 4, 4, 3, 3, 4, 1, 3] }
		],
		Expected={
			Recognized=["archer", "qatal_duelist", "reload_ranged"],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "tank", "tank_banner"],
			Anchor="qatal_duelist",
			SharedFuture={ hitpoints_max=59.0, resolve=37.0, fatigue=97.0, melee_skill=75.0, ranged_skill=39.0, melee_defense=22.0, ranged_defense=9.0, initiative=159.0 },
			SecondaryQualified=["archer", "reload_ranged"],
			Selected=["qatal_duelist", "reload_ranged", "archer", "tempo"]
		}
	},
	{
		ID="hybrid_narrow_fail_3", Category="hybrid_narrow_fail",
		ForcedAnchorID="support_frontliner",
		Body={
			Seed=15971576530312179416, RecruitUID=15971576530312179416, RecruitName="Parity hybrid_narrow_fail_3",
			BackgroundID="background.manual", BackgroundName="Eunuch",
			TraitIDs=["trait.sure footing"], TraitNames=["Sure Footing"],
			Stats={ hitpoints_max=57.0, resolve=29.0, fatigue=95.0, melee_skill=55.0, ranged_skill=38.0, melee_defense=8.0, ranged_defense=3.0, initiative=104.0 }, Stars={ hitpoints_max=1, resolve=0, fatigue=0, melee_skill=1, ranged_skill=0, melee_defense=2, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=2, fatigue=2, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=2}, Ordered=[3, 2, 2, 5, 3, 2, 3, 2] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 4, 4, 3, 3, 3, 4] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 4, 4, 2, 4, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=4, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=2}, Ordered=[4, 2, 4, 4, 2, 2, 3, 2] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 3, 4, 2, 3, 3, 2] },
			{ Level=7, Rolls={hitpoints_max=3, resolve=2, fatigue=2, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=2}, Ordered=[3, 2, 2, 5, 2, 2, 3, 2] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 4, 5, 3, 4, 3, 2] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 3, 4, 2, 3, 3, 2] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 4, 3, 4, 3, 3] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=2, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 2, 4, 4, 3, 3, 3, 3] }
		],
		Expected={
			Recognized=["duelist", "fatigue_carry", "qatal_duelist", "support_frontliner", "tank", "tank_banner"],
			Reachable=["archer", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank", "tank_banner"],
			Anchor="support_frontliner",
			SharedFuture={ hitpoints_max=92.0, resolve=29.0, fatigue=95.0, melee_skill=80.0, ranged_skill=38.0, melee_defense=38.0, ranged_defense=3.0, initiative=104.0 },
			SecondaryQualified=["duelist", "fatigue_carry", "qatal_duelist", "tank", "tank_banner"],
			Selected=["support_frontliner", "tank", "fatigue_carry", "tank_banner"]
		}
	},
	{
		ID="unusual_weak_1", Category="unusual_weak",
		ForcedAnchorID="archer",
		Body={
			Seed=3811550288750824954, RecruitUID=3811550288750824954, RecruitName="Parity unusual_weak_1",
			BackgroundID="background.manual", BackgroundName="Servant",
			TraitIDs=["trait.superstitious"], TraitNames=["Superstitious"],
			Stats={ hitpoints_max=52.0, resolve=35.0, fatigue=89.0, melee_skill=48.0, ranged_skill=34.0, melee_defense=2.0, ranged_defense=5.0, initiative=108.0 }, Stars={ hitpoints_max=1, resolve=1, fatigue=0, melee_skill=0, ranged_skill=1, melee_defense=2, ranged_defense=1, initiative=2 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 2, 5, 2, 4, 3, 4] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 4, 4, 5, 3, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 3, 4, 5, 2, 4, 3, 3] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 4, 5, 2, 4, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=2, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 2, 5, 2, 3, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=3, resolve=3, fatigue=3, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 3, 3, 5, 3, 4, 3, 4] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 4, 5, 1, 4, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 3, 5, 2, 3, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=3, fatigue=2, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 2, 5, 3, 3, 3, 4] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 3, 3, 5, 2, 4, 3, 4] }
		],
		Expected={
			Recognized=["archer", "hybrid", "qatal_duelist", "reload_ranged", "support_frontliner", "tank"],
			Reachable=["archer", "pure_thrower", "reload_ranged", "tank", "tank_banner"],
			Anchor="archer",
			SharedFuture={ hitpoints_max=52.0, resolve=35.0, fatigue=89.0, melee_skill=48.0, ranged_skill=71.0, melee_defense=2.0, ranged_defense=42.0, initiative=158.0 },
			SecondaryQualified=["pure_thrower", "qatal_duelist", "reload_ranged", "support_frontliner", "tank"],
			Selected=["archer", "reload_ranged", "pure_thrower", "qatal_duelist"]
		}
	},
	{
		ID="unusual_weak_2", Category="unusual_weak",
		ForcedAnchorID="tank",
		Body={
			Seed=5059547236801832708, RecruitUID=5059547236801832708, RecruitName="Parity unusual_weak_2",
			BackgroundID="background.manual", BackgroundName="Farmhand",
			TraitIDs=[], TraitNames=[],
			Stats={ hitpoints_max=62.0, resolve=28.0, fatigue=100.0, melee_skill=49.0, ranged_skill=37.0, melee_defense=3.0, ranged_defense=5.0, initiative=107.0 }, Stars={ hitpoints_max=0, resolve=3, fatigue=0, melee_skill=0, ranged_skill=0, melee_defense=2, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=2, resolve=4, fatigue=4, initiative=3, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=3}, Ordered=[2, 4, 4, 3, 3, 2, 3, 3] },
			{ Level=3, Rolls={hitpoints_max=2, resolve=5, fatigue=3, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[2, 5, 3, 5, 1, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 3, 4, 2, 3, 3, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 3, 5, 1, 4, 3, 3] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=5, fatigue=2, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 5, 2, 5, 2, 2, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=2, resolve=5, fatigue=2, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[2, 5, 2, 5, 3, 3, 3, 2] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=5, fatigue=4, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[4, 5, 4, 3, 3, 3, 3, 2] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=5, fatigue=3, initiative=3, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=2}, Ordered=[3, 5, 3, 3, 1, 4, 3, 2] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=5, fatigue=2, initiative=5, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 5, 2, 5, 3, 3, 3, 3] },
			{ Level=11, Rolls={hitpoints_max=2, resolve=4, fatigue=3, initiative=3, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=2}, Ordered=[2, 4, 3, 3, 2, 4, 3, 2] }
		],
		Expected={
			Recognized=["duelist", "support_frontliner", "tank"],
			Reachable=["archer", "pure_thrower", "reload_ranged", "tank", "tank_banner"],
			Anchor="tank",
			SharedFuture={ hitpoints_max=91.0, resolve=60.0, fatigue=109.0, melee_skill=49.0, ranged_skill=37.0, melee_defense=33.0, ranged_defense=5.0, initiative=107.0 },
			SecondaryQualified=["duelist", "fatigue_carry", "qatal_duelist", "support_frontliner", "tank_banner"],
			Selected=["tank", "tank_banner", "fatigue_carry", "duelist"]
		}
	},
	{
		ID="unusual_weak_3", Category="unusual_weak",
		ForcedAnchorID="pure_thrower",
		Body={
			Seed=14043008227644808060, RecruitUID=14043008227644808060, RecruitName="Parity unusual_weak_3",
			BackgroundID="background.manual", BackgroundName="Wildman",
			TraitIDs=["trait.brute", "trait.iron jaw"], TraitNames=["Brute", "Iron Jaw"],
			Stats={ hitpoints_max=62.0, resolve=42.0, fatigue=111.0, melee_skill=49.0, ranged_skill=39.0, melee_defense=1.0, ranged_defense=-1.0, initiative=97.0 }, Stars={ hitpoints_max=1, resolve=1, fatigue=2, melee_skill=0, ranged_skill=2, melee_defense=0, ranged_defense=0, initiative=1 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=4, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[4, 4, 4, 4, 1, 4, 3, 3] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[3, 4, 4, 4, 3, 4, 2, 3] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=1, ranged_defense=3}, Ordered=[4, 4, 4, 5, 1, 4, 1, 3] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=4}, Ordered=[4, 4, 4, 4, 2, 4, 1, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=1, ranged_defense=2}, Ordered=[4, 3, 4, 5, 1, 4, 1, 2] },
			{ Level=7, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=1, ranged_defense=4}, Ordered=[3, 3, 4, 5, 3, 4, 1, 4] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[3, 4, 4, 4, 2, 4, 3, 3] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=1, ranged_defense=2}, Ordered=[4, 4, 4, 5, 1, 4, 1, 2] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=1, ranged_defense=2}, Ordered=[3, 3, 4, 5, 2, 4, 1, 2] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 4, 5, 1, 4, 3, 2] }
		],
		Expected={
			Recognized=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "reload_ranged", "tank", "tank_banner"],
			Reachable=["archer", "injury_specialist", "pure_thrower", "reload_ranged", "tank", "tank_banner"],
			Anchor="pure_thrower",
			SharedFuture={ hitpoints_max=62.0, resolve=42.0, fatigue=151.0, melee_skill=49.0, ranged_skill=79.0, melee_defense=1.0, ranged_defense=27.0, initiative=97.0 },
			SecondaryQualified=["archer", "attack_banner", "duelist", "fatigue_carry", "injury_specialist", "reload_ranged", "tank", "tank_banner"],
			Selected=["pure_thrower", "tank", "injury_specialist", "attack_banner"]
		}
	},
	{
		ID="fallback_1", Category="fallback",
		ForcedAnchorID="tank",
		Body={
			Seed=8643806257402628233, RecruitUID=8643806257402628233, RecruitName="Parity fallback_1",
			BackgroundID="background.manual", BackgroundName="Mason",
			TraitIDs=[], TraitNames=[],
			Stats={ hitpoints_max=50.0, resolve=33.0, fatigue=97.0, melee_skill=56.0, ranged_skill=39.0, melee_defense=4.0, ranged_defense=1.0, initiative=109.0 }, Stars={ hitpoints_max=0, resolve=1, fatigue=1, melee_skill=0, ranged_skill=0, melee_defense=1, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=2, ranged_defense=3}, Ordered=[3, 3, 4, 5, 3, 2, 2, 3] },
			{ Level=3, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 3, 3, 3, 3, 3, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 4, 5, 2, 3, 2, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=5, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 4, 5, 1, 4, 3, 4] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=1, ranged_skill=2, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 3, 4, 1, 2, 2, 4] },
			{ Level=7, Rolls={hitpoints_max=2, resolve=3, fatigue=3, initiative=4, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=3}, Ordered=[2, 3, 3, 4, 2, 2, 3, 3] },
			{ Level=8, Rolls={hitpoints_max=4, resolve=4, fatigue=3, initiative=3, melee_skill=1, ranged_skill=2, melee_defense=2, ranged_defense=4}, Ordered=[4, 4, 3, 3, 1, 2, 2, 4] },
			{ Level=9, Rolls={hitpoints_max=4, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 3, 5, 2, 4, 3, 4] },
			{ Level=10, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=4, melee_skill=1, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 4, 3, 4, 1, 4, 3, 4] },
			{ Level=11, Rolls={hitpoints_max=4, resolve=3, fatigue=4, initiative=4, melee_skill=2, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[4, 3, 4, 4, 2, 2, 3, 4] }
		],
		Expected={
			Recognized=[],
			Reachable=["archer", "attack_banner", "duelist", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "tank", "tank_banner"],
			Anchor="tank",
			SharedFuture={ hitpoints_max=84.0, resolve=61.0, fatigue=104.0, melee_skill=56.0, ranged_skill=39.0, melee_defense=30.0, ranged_defense=1.0, initiative=109.0 },
			SecondaryQualified=["duelist", "fatigue_carry"],
			Selected=["tank", "fatigue_carry", "duelist", "tempo"]
		}
	},
	{
		ID="fallback_2", Category="fallback",
		ForcedAnchorID="archer",
		Body={
			Seed=5912440106831420576, RecruitUID=5912440106831420576, RecruitName="Parity fallback_2",
			BackgroundID="background.manual", BackgroundName="Anatomist",
			TraitIDs=["trait.drunkard", "trait.night owl"], TraitNames=["Drunkard", "Night Owl"],
			Stats={ hitpoints_max=56.0, resolve=46.0, fatigue=91.0, melee_skill=50.0, ranged_skill=39.0, melee_defense=5.0, ranged_defense=4.0, initiative=105.0 }, Stars={ hitpoints_max=0, resolve=0, fatigue=0, melee_skill=1, ranged_skill=0, melee_defense=0, ranged_defense=1, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=3, resolve=2, fatigue=4, initiative=4, melee_skill=3, ranged_skill=2, melee_defense=1, ranged_defense=3}, Ordered=[3, 2, 4, 4, 3, 2, 1, 3] },
			{ Level=3, Rolls={hitpoints_max=2, resolve=3, fatigue=2, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=3}, Ordered=[2, 3, 2, 3, 3, 4, 3, 3] },
			{ Level=4, Rolls={hitpoints_max=3, resolve=3, fatigue=2, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[3, 3, 2, 5, 3, 4, 3, 4] },
			{ Level=5, Rolls={hitpoints_max=4, resolve=2, fatigue=3, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[4, 2, 3, 3, 3, 4, 2, 4] },
			{ Level=6, Rolls={hitpoints_max=3, resolve=3, fatigue=3, initiative=4, melee_skill=2, ranged_skill=3, melee_defense=1, ranged_defense=3}, Ordered=[3, 3, 3, 4, 2, 3, 1, 3] },
			{ Level=7, Rolls={hitpoints_max=2, resolve=3, fatigue=3, initiative=5, melee_skill=2, ranged_skill=2, melee_defense=2, ranged_defense=3}, Ordered=[2, 3, 3, 5, 2, 2, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=3, fatigue=4, initiative=3, melee_skill=3, ranged_skill=2, melee_defense=3, ranged_defense=4}, Ordered=[3, 3, 4, 3, 3, 2, 3, 4] },
			{ Level=9, Rolls={hitpoints_max=2, resolve=2, fatigue=4, initiative=5, melee_skill=3, ranged_skill=2, melee_defense=2, ranged_defense=4}, Ordered=[2, 2, 4, 5, 3, 2, 2, 4] },
			{ Level=10, Rolls={hitpoints_max=2, resolve=3, fatigue=2, initiative=3, melee_skill=3, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[2, 3, 2, 3, 3, 3, 2, 4] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=4, fatigue=3, initiative=3, melee_skill=2, ranged_skill=3, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 3, 3, 2, 3, 2, 4] }
		],
		Expected={
			Recognized=[],
			Reachable=["archer", "attack_banner", "fatigue_carry", "pure_thrower", "qatal_duelist", "reload_ranged", "tank", "tank_banner"],
			Anchor="archer",
			SharedFuture={ hitpoints_max=56.0, resolve=46.0, fatigue=91.0, melee_skill=50.0, ranged_skill=68.0, melee_defense=5.0, ranged_defense=40.0, initiative=143.0 },
			SecondaryQualified=["reload_ranged"],
			Selected=["archer", "reload_ranged", "pure_thrower", "tempo"]
		}
	},
	{
		ID="fallback_3", Category="fallback",
		ForcedAnchorID="support_frontliner",
		Body={
			Seed=5610075808276255185, RecruitUID=5610075808276255185, RecruitName="Parity fallback_3",
			BackgroundID="background.manual", BackgroundName="Tailor",
			TraitIDs=["trait.fear of greenskins"], TraitNames=["Fear of Greenskins"],
			Stats={ hitpoints_max=57.0, resolve=26.0, fatigue=87.0, melee_skill=52.0, ranged_skill=37.0, melee_defense=2.0, ranged_defense=4.0, initiative=106.0 }, Stars={ hitpoints_max=1, resolve=3, fatigue=2, melee_skill=0, ranged_skill=1, melee_defense=0, ranged_defense=0, initiative=0 }
		},
		Screens=[
			{ Level=2, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=3}, Ordered=[4, 4, 4, 3, 2, 3, 3, 3] },
			{ Level=3, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=4, melee_skill=2, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[3, 4, 4, 4, 2, 4, 2, 4] },
			{ Level=4, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 4, 5, 3, 4, 2, 3] },
			{ Level=5, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=3, melee_skill=3, ranged_skill=4, melee_defense=2, ranged_defense=4}, Ordered=[3, 5, 4, 3, 3, 4, 2, 4] },
			{ Level=6, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=4, melee_skill=3, ranged_skill=4, melee_defense=3, ranged_defense=4}, Ordered=[4, 4, 4, 4, 3, 4, 3, 4] },
			{ Level=7, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=3, melee_skill=1, ranged_skill=4, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 4, 3, 1, 4, 2, 3] },
			{ Level=8, Rolls={hitpoints_max=3, resolve=4, fatigue=4, initiative=5, melee_skill=2, ranged_skill=3, melee_defense=3, ranged_defense=2}, Ordered=[3, 4, 4, 5, 2, 3, 3, 2] },
			{ Level=9, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=3, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=2}, Ordered=[3, 5, 4, 3, 1, 3, 2, 2] },
			{ Level=10, Rolls={hitpoints_max=4, resolve=4, fatigue=4, initiative=5, melee_skill=1, ranged_skill=3, melee_defense=2, ranged_defense=3}, Ordered=[4, 4, 4, 5, 1, 3, 2, 3] },
			{ Level=11, Rolls={hitpoints_max=3, resolve=5, fatigue=4, initiative=4, melee_skill=3, ranged_skill=3, melee_defense=1, ranged_defense=3}, Ordered=[3, 5, 4, 4, 3, 3, 1, 3] }
		],
		Expected={
			Recognized=["hybrid"],
			Reachable=["archer", "attack_banner", "pure_thrower", "reload_ranged", "tank", "tank_banner"],
			Anchor="support_frontliner",
			SharedFuture={ hitpoints_max=92.0, resolve=26.0, fatigue=87.0, melee_skill=73.0, ranged_skill=37.0, melee_defense=24.0, ranged_defense=4.0, initiative=106.0 },
			SecondaryQualified=[],
			Selected=["support_frontliner", "tank", "tempo", "tank_banner"]
		}
	}
];


::Brotherhood.parentArraysEqual <- function( _left, _right )
{
	if (_left == null || _right == null) return _left == _right;
	if (_left.len() != _right.len()) return false;
	for (local i = 0; i < _left.len(); ++i)
		if (_left[i] != _right[i]) return false;
	return true;
}

::Brotherhood.parentStatsNearlyEqual <- function( _left, _right, _epsilon = 0.0001 )
{
	foreach (name, value in _right)
	{
		if (!(name in _left)) return false;
		if (::Math.abs(_left[name].tofloat() - value.tofloat()) > _epsilon) return false;
	}
	return true;
}

::Brotherhood.runParentParityFixture <- function()
{
	local failures = [];
	local passes = 0;
	foreach (fixture in ::Brotherhood.ParentParityFixtures)
	{
		try
		{
			local result = ::Brotherhood.generateParentSelection(fixture.Body, ::Brotherhood.ParentProfiles, 4, fixture.Screens, {
				ForcedAnchorID = fixture.ForcedAnchorID,
				RunSeed = fixture.Body.Seed,
				BodyIndex = 0,
				PreviousGroup = null,
				DisableGroupSaturation = true
			});
			local selected = result.Selected.map(@(_score) _score.Profile.ID);
			local expected = fixture.Expected;
			if (result.Anchor == null || result.Anchor.Profile.ID != expected.Anchor)
				throw "anchor mismatch: expected " + expected.Anchor + ", got " + (result.Anchor == null ? "null" : result.Anchor.Profile.ID);
			if (!::Brotherhood.parentArraysEqual(selected, expected.Selected))
				throw "selected mismatch: expected [" + ::Brotherhood.parentJoin(expected.Selected, ",") + "], got [" + ::Brotherhood.parentJoin(selected, ",") + "]";
			if (!::Brotherhood.parentStatsNearlyEqual(result.SharedFuture, expected.SharedFuture))
				throw "shared-future mismatch";
			local recognized = [];
			local reachable = [];
			foreach (cost in result.ProposalCosts)
			{
				if (cost.Recognition.Qualified) recognized.push(cost.Profile.ID);
				if (cost.Reachability.Qualified) reachable.push(cost.Profile.ID);
			}
			recognized.sort(@(a, b) a <=> b);
			reachable.sort(@(a, b) a <=> b);
			if (!::Brotherhood.parentArraysEqual(recognized, expected.Recognized))
				throw "recognized mismatch";
			if (!::Brotherhood.parentArraysEqual(reachable, expected.Reachable))
				throw "reachable mismatch";
			local secondary = [];
			foreach (item in result.SecondaryDiagnostics)
				if (item.IdentityQualified) secondary.push(item.Profile.ID);
			secondary.sort(@(a, b) a <=> b);
			if (!::Brotherhood.parentArraysEqual(secondary, expected.SecondaryQualified))
				throw "secondary-qualified mismatch";
			passes += 1;
			::logInfo("[Brotherhood][PARENT][PARITY] PASS " + fixture.ID + " selected=[" + ::Brotherhood.parentJoin(selected, ",") + "]");
		}
		catch (error)
		{
			failures.push(fixture.ID + ": " + error);
			::logError("[Brotherhood][PARENT][PARITY] FAIL " + fixture.ID + ": " + error);
		}
	}
	if (failures.len() != 0)
		throw "parent parity fixtures failed (" + failures.len() + "/" + ::Brotherhood.ParentParityFixtures.len() + "): " + ::Brotherhood.parentJoin(failures, " | ");
	::logInfo("[Brotherhood][PARENT][PARITY] ALL PASS count=" + passes);
	return true;
}
