// Packaged runtime representation of the current reviewed 0M parent profiles.
// Regenerated by tools/sync_parent_runtime_data.py — do not hand-edit thresholds.
// The external Obsidian vault is authoring input and is never read at runtime.
::Brotherhood.ParentProfileSource <- {
	FormatVersion = 3,
	Fingerprint = "c770e5b6162820b6c793010eb5893ae6611af3b97ed4381ee944973543755e6c",
	Profiles = [
		{
			SchemaVersion=1, ID="archer", Name="Archer", Source="0M Archer.md", BuildSource="0B Archer.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["bow", "headshot", "vision", "cloth_armor"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=10.0, Acceptable=25.0, Great=30.0, Premium=35.0, Importance=1.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=100.0, Acceptable=120.0, Great=135.0, Premium=145.0, Importance=2.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="attack_banner", Name="Attack Banner", Source="0M Attack Banner.md", BuildSource="0B Attack Banner.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["polearm", "morale"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=2.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=80.0, Acceptable=90.0, Great=100.0, Premium=110.0, Importance=1.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=40.0, Acceptable=55.0, Great=75.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="duelist", Name="Duelist", Source="0M Duelist.md", BuildSource="0B Duelist.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["sword", "lone", "light_armor", "free_offhand"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=19.0, Acceptable=24.0, Great=30.0, Premium=35.0, Importance=2.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=80.0, Acceptable=90.0, Great=100.0, Premium=110.0, Importance=1.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="fatigue_carry", Name="Fatigue Carry", Source="0M Fatigue Carry.md", BuildSource="0B Fatigue Carry.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["axe", "fatigue", "kill_chain", "gap_closer"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=19.0, Acceptable=24.0, Great=30.0, Premium=35.0, Importance=1.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=80.0, Acceptable=90.0, Great=100.0, Premium=110.0, Importance=2.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="hybrid", Name="Hybrid", Source="0M Hybrid.md", BuildSource="0B Hybrid.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["hybrid", "evasion", "inventory"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=2.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness={ MinimumProjectedSide=70.0, DeadSideBelow=55.0, AptitudeOneAt=60.0, AptitudeStep=10.0, MinimumAnchorEvidence=0.12, WeakerWeight=0.8, StrongerWeight=0.2, Sides=[
				{ Name="melee", Members=["melee_skill"] },
				{ Name="ranged", Members=["ranged_skill"] }
			] }
		},
		{
			SchemaVersion=1, ID="injury_specialist", Name="Injury Specialist", Source="0M Injury Specialist.md", BuildSource="0B Injury Specialist.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["injury"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=1.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=1.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[
				{ Name="attack_skill", Members=["melee_skill", "ranged_skill"] }
			],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="pure_thrower", Name="Pure Thrower", Source="0M Pure Thrower.md", BuildSource="0B Pure Thrower.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["throwing", "safety"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=19.0, Acceptable=24.0, Great=30.0, Premium=35.0, Importance=1.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=80.0, Acceptable=90.0, Great=100.0, Premium=110.0, Importance=2.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="qatal_duelist", Name="Qatal Duelist", Source="0M Qatal Duelist.md", BuildSource="0B Qatal Duelist.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["dagger", "initiative", "cloth_armor", "finisher", "gap_closer"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=10.0, Acceptable=25.0, Great=30.0, Premium=35.0, Importance=1.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=100.0, Acceptable=120.0, Great=135.0, Premium=145.0, Importance=2.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="reload_ranged", Name="Reload Ranged", Source="0M Reload Ranged.md", BuildSource="0B Reload Ranged.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["crossbow", "handgonne", "safety", "cloth_armor", "consumable"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=10.0, Acceptable=25.0, Great=30.0, Premium=35.0, Importance=1.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=100.0, Acceptable=120.0, Great=135.0, Premium=145.0, Importance=2.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="support_frontliner", Name="Support Frontliner", Source="0M Support Frontliner.md", BuildSource="0B Support Frontliner.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=[],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=65.0, Acceptable=85.0, Great=90.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=10.0, Acceptable=25.0, Great=30.0, Premium=35.0, Importance=2.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[
				{ Name="low_fatigue", IsRelational=false, RequiresQualified=[], ExcludesQualified=[], Importance=3.0, Stat="fatigue", ActivatesBelow=90.0, Preference="lower" }
			],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="tank", Name="Tank", Source="0M Tank.md", BuildSource="0B Tank.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["tank"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=10.0, Acceptable=25.0, Great=30.0, Premium=35.0, Importance=3.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=55.0, Acceptable=70.0, Great=85.0, Premium=95.0, Importance=2.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=80.0, Acceptable=90.0, Great=100.0, Premium=110.0, Importance=1.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=20.0, Acceptable=40.0, Great=50.0, Premium=60.0, Importance=1.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="tank_banner", Name="Tank Banner", Source="0M Tank Banner.md", BuildSource="0B Tank Banner.canvas", ReviewStatus="reviewed", Tempo=false,
			Classes=["morale", "tank"],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=10.0, Acceptable=25.0, Great=30.0, Premium=35.0, Importance=1.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=55.0, Acceptable=70.0, Great=85.0, Premium=95.0, Importance=2.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=40.0, Acceptable=55.0, Great=75.0, Premium=95.0, Importance=3.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		},
		{
			SchemaVersion=1, ID="tempo", Name="Tempo", Source="0M Tempo.md", BuildSource="0B Tempo.canvas", ReviewStatus="reviewed", Tempo=true,
			Classes=[],
			Stats=[
				{ Name="melee_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="melee_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_skill", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="ranged_defense", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="hitpoints_max", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="fatigue", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="resolve", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" },
				{ Name="initiative", IneligibleBelow=null, Bad=null, Acceptable=null, Great=null, Premium=null, Importance=0.0, Direction="higher" }
			],
			Alternatives=[],
			RoutingClaims=[],
			ConjunctiveFitness=null
		}
	]
};
