// Auto-generated by tools/sync_perk_stars.py - do not edit by hand.
// Source: Obsidian ## Stars joined through ActiveObsidianPerks Note names.
if (!("Brotherhood" in getroottable())) return;

::Brotherhood.PerkStars <- {
	["perk.colossus"] = [], // Colossus <- T1 - Colossus.md
	["perk.nine_lives"] = [], // Nine Lives <- T1 - Nine Lives.md
	["perk.bh_mind_over_matter"] = [], // Will <- T1 - Will.md
	["perk.bh_vigor"] = [], // Vigor <- T1 - Vigor.md
	["perk.pathfinder"] = ["terrain"], // Pathfinder <- T1 - Pathfinder.md
	["perk.bags_and_belts"] = ["inventory"], // Bags and Belts <- T1 - Bags and Belts.md
	["perk.fortified_mind"] = ["morale"], // Fortified Mind <- T2 - Fortified Mind.md
	["perk.steel_brow"] = ["heavy_armor"], // Steel Brow <- T2 - Steel Brow.md
	["perk.brawny"] = ["heavy_armor", "medium_armor", "fatigue"], // Brawny <- T3 - Brawny.md
	["perk.dodge"] = ["initiative", "evasion"], // Dodge <- T2 - Dodge.md
	["perk.bh_overwhelm"] = ["initiative", "suppression"], // Overwhelm <- T5 - Overwhelm.md
	["perk.bh_footwork"] = ["safety", "bow", "crossbow", "throwing", "handgonne"], // Footwork <- T5 - Footwork.md
	["perk.berserk"] = ["kill_chain"], // Berserk <- T6 - Berserk.md
	["perk.head_hunter"] = ["headshot"], // Head Hunter <- T6 - Head Hunter.md
	["perk.killing_frenzy"] = ["kill_chain"], // Killing Frenzy <- T7 - Killing Frenzy.md
	["perk.bh_small_head"] = ["headshot"], // Small Head <- T1 - Small Head.md
	["perk.bh_fast_adaptation"] = ["miss_economy"], // Fast Adaptation <- T1 - Fast Adaptation.md
	["perk.bh_crippling_strikes"] = ["injury"], // Crippling Strikes <- T1 - Crippling Strikes.md
	["perk.bh_quick_hands"] = [], // Quick Hands <- T2 - Quick Hands.md
	["perk.bh_executioner"] = ["injury", "finisher"], // Executioner <- T2 - Executioner.md
	["perk.bh_bullseye"] = [], // Bullseye <- T2 - Bullseye.md
	["perk.bh_feint"] = ["miss_economy", "initiative"], // Feint <- T2 - Feint.md
	["perk.bh_easy_target"] = [], // Easy Target <- T2 - Easy Target.md
	["perk.bh_examination"] = [], // Examination <- T2 - Examination.md
	["perk.bh_steady_rhythm"] = [], // Steady Rhythm <- T3 - Steady Rhythm.md
	["perk.bh_lightweight"] = ["fatigue"], // Lightweight <- T3 - Lightweight.md
	["perk.bh_relentless"] = ["initiative"], // Relentless <- T3 - Relentless.md
	["perk.bh_pursuer"] = ["kill_chain", "gap_closer"], // Pursuer <- T3 - Pursuer.md
	["perk.bh_ghost_pain"] = ["injury"], // Ghost Pain <- T3 - Ghost Pain.md
	["perk.bh_torture"] = ["injury"], // Torture <- T3 - Torture.md
	["perk.bh_shock"] = ["injury"], // Shock <- T3 - Shock.md
	["perk.bh_hammer_mastery"] = ["hammer"], // Hammer Mastery <- T4 - Hammer Mastery.md
	["perk.bh_mace_mastery"] = ["mace", "daze"], // Mace Mastery <- T4 - Mace Mastery.md
	["perk.bh_axe_mastery"] = ["axe"], // Axe Mastery <- T4 - Axe Mastery.md
	["perk.bh_cleaver_mastery"] = ["cleaver", "injury"], // Cleaver Mastery <- T4 - Cleaver Mastery.md
	["perk.bh_sword_mastery"] = ["sword"], // Sword Mastery <- T4 - Sword Mastery.md
	["perk.bh_dagger_mastery"] = ["dagger", "initiative"], // Dagger Mastery <- T4 - Dagger Mastery.md
	["perk.bh_bow_mastery"] = ["bow"], // Bow Mastery <- T4 - Bow Mastery.md
	["perk.bh_underdog"] = ["outnumbered", "tank"], // Underdog <- T5 - Underdog.md
	["perk.lone_wolf"] = ["lone"], // Lone Wolf <- T5 - Lone Wolf.md
	["perk.bh_disrupt"] = ["suppression"], // Disrupt <- T5 - Disrupt.md
	["perk.bh_lunge"] = ["gap_closer"], // Lunge <- T5 - Lunge.md
	["perk.bh_medieval_medicine"] = ["injury"], // Medieval Medicine <- T5 - Medieval Medicine.md
	["perk.bh_finesse"] = ["evasion"], // Finesse <- T6 - Finesse.md
	["perk.bh_crimson"] = ["injury"], // Crimson <- T6 - Crimson.md
	["perk.bh_duelist"] = ["free_offhand", "lone"], // Duelist <- T7 - Duelist.md
	["perk.bh_flow_state"] = ["free_offhand"], // Flow State <- T7 - Flow State.md
	["perk.bh_outmatched"] = ["free_offhand", "lone", "outnumbered"], // Outmatched <- T7 - Outmatched.md
	["perk.bh_fearsome"] = ["morale"], // Fearsome <- T7 - Fearsome.md
	["perk.bh_preparation"] = ["inventory", "throwing", "handgonne"], // Preparation <- T1 - Preparation.md
	["perk.bh_bloodloaded"] = [], // Bloodloaded <- T2 - Bloodloaded.md
	["perk.bh_desperation"] = ["inventory", "bow", "crossbow"], // Desperation <- T2 - Desperation.md
	["perk.bh_porcupine"] = ["bow"], // Point Blank <- T3 - Point Blank.md
	["perk.bh_versatile_defense"] = ["hybrid"], // Versatile Defense <- T3 - Versatile Defense.md
	["perk.bh_juggling_mastery"] = ["throwing"], // Juggling Mastery <- T4 - Juggling Mastery.md
	["perk.bh_skirmishing_mastery"] = ["throwing"], // Skirmishing Mastery <- T4 - Skirmishing Mastery.md
	["perk.bh_volley_mastery"] = ["throwing"], // Volley Mastery <- T4 - Volley Mastery.md
	["perk.bh_asymmetry"] = ["hybrid"], // Asymmetry <- T5 - Asymmetry.md
	["perk.bh_exceptional_skill"] = ["bow", "crossbow", "handgonne"], // Exceptional Skill <- T5 - Exceptional Skill.md
	["perk.bh_malice"] = ["hybrid"], // Malice <- T5 - Malice.md
	["perk.bh_omnivorous"] = ["hybrid"], // Omnivorous <- T5 - Omnivorous.md
	["perk.bh_steady_aim"] = ["bow"], // Steady Aim <- T5 - Steady Aim.md
	["perk.bh_windreaver"] = ["bow"], // Windreaver <- T5 - Windreaver.md
	["perk.bh_cooking_up_trouble"] = [], // Cooking Up Trouble <- T6 - Cooking Up Trouble.md
	["perk.bh_distracted"] = ["throwing", "enemy_behavior", "bow", "crossbow"], // Distracted <- T7 - Distracted.md
	["perk.bh_over_dexterous"] = [], // Over-Dexterous <- T7 - Over-Dexterous.md
	["perk.bh_student"] = [], // Student <- T1 - Student.md
	["perk.bh_gifted"] = [], // Gifted <- T2 - Gifted.md
	["perk.bh_fine_balance"] = [], // Fine Balance <- T2 - Fine Balance.md
	["perk.bh_fundamentals"] = [], // Fundamentals <- T2 - Fundamentals.md
	["perk.bh_bully"] = ["suppression"], // Bully <- T1 - Bully.md
	["perk.bh_acuity"] = ["initiative"], // Acuity <- T1 - Acuity.md
	["perk.bh_unadaptive_opening"] = ["miss_economy"], // Unadaptive Opening <- T1 - Unadaptive Opening.md
	["perk.bh_determination"] = ["morale"], // Determination <- T2 - Determination.md
	["perk.bh_off_guard"] = ["turn_priority"], // Off Guard <- T2 - Off Guard.md
	["perk.bh_anticipation"] = ["evasion", "vision"], // Anticipation <- T3 - Anticipation.md
	["perk.rally_the_troops"] = ["morale"], // Rally the Troops <- T3 - Rally the Troops.md
	["perk.bh_lead_by_example"] = ["morale"], // Lead by Example <- T3 - Lead by Example.md
	["perk.rotation"] = ["tank"], // Rotation <- T3 - Rotation.md
	["perk.taunt"] = ["enemy_behavior", "tank"], // Taunt <- T3 - Taunt.md
	["perk.bh_heavyweight"] = ["miss_economy"], // Heavyweight <- T3 - Heavyweight.md
	["perk.bh_polearm_mastery"] = ["polearm"], // Polearm Mastery <- T4 - Polearm Mastery.md
	["perk.bh_shield_mastery"] = ["shield", "tank"], // Shield Mastery <- T4 - Shield Mastery.md
	["perk.bh_gunpowder_mastery"] = ["handgonne"], // Gunpowder Mastery <- T4 - Gunpowder Mastery.md
	["perk.bh_crossbow_mastery"] = ["crossbow"], // Crossbow Mastery <- T4 - Crossbow Mastery.md
	["perk.bh_consumable_mastery"] = ["inventory", "consumable"], // Consumable Mastery <- T4 - Consumable Mastery.md
	["perk.bh_spear_mastery"] = ["spear"], // Spear Mastery <- T4 - Spear Mastery.md
	["perk.bh_breach"] = ["suppression"], // Breach <- T5 - Breach.md
	["perk.bh_snapping_turtle"] = ["tank"], // Snapping Turtle <- T6 - Snapping Turtle.md
	["perk.bh_sentinel"] = ["tank"], // Sentinel <- T6 - Sentinel.md
	["perk.bh_nidhogg"] = ["enemy_behavior", "kill_chain"], // Nidhogg <- T6 - Nidhogg.md
	["perk.bh_ragnarok"] = ["kill_chain"], // Ragnarok <- T6 - Ragnarok.md
	["perk.bh_overkill"] = ["kill_chain"], // Overkill <- T7 - Overkill.md
	["perk.bh_nerves_of_steel"] = ["tank"], // Nerves of Steel <- T7 - Nerves of Steel.md
	["perk.bh_opening_metal"] = ["suppression"], // Opening Metal <- T7 - Opening Metal.md
	["perk.bh_aimed_sloth"] = ["fatigue"], // Aimed Sloth <- T7 - Aimed Sloth.md
	["perk.indomitable"] = ["tank"], // Indomitable <- T7 - Indomitable.md
};

::Brotherhood.getPerkStars <- function( _perkID )
{
	if (typeof _perkID != "string" || !(_perkID in ::Brotherhood.PerkStars)) return [];
	return ::Brotherhood.PerkStars[_perkID];
};

