this.bh_duel_skill <- this.inherit("scripts/skills/skill", {
	m={},
	function create(){this.m.ID="actives.bh_duel";this.m.Name="Duel";this.m.Description="Challenge one enemy to a duel until either duelist dies or the target's morale is broken.";this.m.Icon="skills/active_14.png";this.m.IconDisabled="skills/active_14_sw.png";this.m.Overlay="active_14";this.m.Type=this.Const.SkillType.Active;this.m.Order=this.Const.SkillOrder.Any-1;this.m.IsActive=true;this.m.IsTargeted=true;this.m.IsAttack=false;this.m.IsIgnoredAsAOO=true;this.m.IsUsingHitchance=false;this.m.ActionPointCost=2;this.m.FatigueCost=10;this.m.MinRange=1;this.m.MaxRange=7;}
	function getPerk(){return this.getContainer()==null?null:this.getContainer().getSkillByID("perk.bh_duel_coward");}
	function getTooltip(){local ret=this.getDefaultUtilityTooltip();ret.push({id=5,type="text",icon="ui/icons/special.png",text="Forces the challenged enemy to prioritize engaging and attacking this character, if possible, throughout the duel"});ret.push({id=6,type="text",icon="ui/icons/melee_skill.png",text="Gain "+::MSU.Text.colorPositive("+10%")+" chance to hit the challenged enemy"});ret.push({id=7,type="text",icon="ui/tooltips/warning.png",text="Suffer "+::MSU.Text.colorNegative("-20%")+" chance to hit every other enemy while the duel lasts"});ret.push({id=8,type="text",icon="ui/icons/morale.png",text="Ends when either duelist dies or the challenged enemy becomes Breaking or Fleeing"});ret.push({id=9,type="text",icon="ui/icons/special.png",text="Only one duel may be active at a time"});return ret;}
	function isUsable(){local perk=this.getPerk();return perk!=null&&perk.validateTarget()==null&&this.skill.isUsable();}
	function onVerifyTarget(_originTile,_targetTile){if(!this.skill.onVerifyTarget(_originTile,_targetTile)||!_targetTile.IsOccupiedByActor)return false;local user=this.getContainer().getActor();local target=_targetTile.getEntity();return target!=null&&!target.isAlliedWith(user)&&target.isAlive()&&target.getMoraleState()!=this.Const.MoraleState.Fleeing&&target.getMoraleState()!=this.Const.MoraleState.Breaking;}
	function onUse(_user,_targetTile){local perk=this.getPerk();if(perk==null)return false;perk.setDuelTarget(_targetTile.getEntity());return true;}
});
