this.bh_load_explosive_bullets_skill <- this.inherit("scripts/skills/skill", {
	m={},
	function create(){this.m.ID="actives.bh_load_explosive_bullets";this.m.Name="Load Explosive Bullets";this.m.Description="Load an empty Handgonne with explosive ammunition. Your next shot deals +60% armor damage and ignores an additional 20% of armor.";this.m.Icon="skills/active_204.png";this.m.IconDisabled="skills/active_204_sw.png";this.m.Overlay="active_204";this.m.SoundOnUse=["sounds/combat/dlc6/reload_gonne_01.wav","sounds/combat/dlc6/reload_gonne_02.wav"];this.m.Type=this.Const.SkillType.Active;this.m.Order=this.Const.SkillOrder.Any-1;this.m.IsActive=true;this.m.IsTargeted=false;this.m.IsAttack=false;this.m.ActionPointCost=9;this.m.FatigueCost=10;this.m.MinRange=0;this.m.MaxRange=0;}
	function getWeapon(){return this.getContainer().getActor().getMainhandItem();}
	function getAmmoItem(){return this.getContainer().getActor().getItems().getItemAtSlot(this.Const.ItemSlot.Ammo);}
	function isHidden(){return this.skill.isHidden() || !::Brotherhood.isHandgonne(this.getWeapon());}
	function isUsable(){local w=this.getWeapon();local a=this.getAmmoItem();return this.skill.isUsable()&&::Brotherhood.isHandgonne(w)&&!w.isLoaded()&&a!=null&&a.getAmmoType()==this.Const.Items.AmmoType.Powder&&a.getAmmo()>=3&&!this.getContainer().hasSkill("effects.bh_explosive_bullets_loaded");}
	function getTooltip(){local ret=this.getDefaultUtilityTooltip();ret.push({id=7,type="text",icon="ui/icons/armor_damage.png",text="The next Handgonne shot deals "+::MSU.Text.colorPositive("+60%")+" armor damage"});ret.push({id=8,type="text",icon="ui/icons/direct_damage.png",text="The next Handgonne shot ignores an additional "+::MSU.Text.colorPositive("20%")+" of armor"});ret.push({id=9,type="text",icon="ui/icons/ammo.png",text="Consumes "+::MSU.Text.colorNegative("3")+" ammunition"});return ret;}
	function onUse(_user,_targetTile){local w=this.getWeapon();local a=this.getAmmoItem();if(w==null||a==null)return false;a.setAmmo(a.getAmmo()-3);w.setLoaded(true);this.getContainer().removeByID("actives.reload_handgonne");this.getContainer().add(this.new("scripts/skills/effects/bh_explosive_bullets_loaded_effect"));::Brotherhood.logArchetypeTest("EXPLOSIVE BULLETS",_user,"Loaded an explosive Handgonne shot and consumed 3 ammunition.");return true;}
});
