this.perk_bh_winner_takes_all <- this.inherit("scripts/skills/skill", {
	m={Stacks=0},
	function create(){this.m.ID="perk.bh_winner_takes_all";this.m.Name="Winner Takes All";this.m.Description=::Brotherhood.getExpansionArchetypeTooltip(this.m.ID);::Brotherhood.applySourcePerkIcon(this,"perk.head_hunter","ui/perks/perk_29.png");this.m.Type=this.Const.SkillType.Perk|this.Const.SkillType.StatusEffect;this.m.Order=this.Const.SkillOrder.Perk;this.m.IsActive=false;this.m.IsHidden=true;}
	function getBonusPerStack(){return ::Math.max(0,::Math.floor(this.getContainer().getActor().getCurrentProperties().getBravery()*0.10));}
	function getTooltip(){local bonus=this.getBonusPerStack()*this.m.Stacks;return [{id=1,type="title",text=this.getName()},{id=2,type="description",text="Kills claimed from marked enemies empower this character for the rest of this fight."},{id=10,type="text",icon="ui/icons/special.png",text="Stacks: "+::MSU.Text.colorPositive(this.m.Stacks)},{id=11,type="text",icon="ui/icons/melee_skill.png",text=::MSU.Text.colorPositive("+"+bonus)+" to Fatigue, Initiative, Melee Attack, Ranged Attack, Melee Defense, and Ranged Defense"},{id=12,type="text",icon="ui/icons/damage_dealt.png",text=::MSU.Text.colorPositive("+"+bonus+"%")+" damage"}];}
	function onUpdate(_properties){this.m.IsHidden=this.m.Stacks==0;if(this.m.Stacks==0)return;local per=::Math.max(0,::Math.floor(_properties.getBravery()*0.10));local bonus=per*this.m.Stacks;_properties.Stamina+=bonus;_properties.Initiative+=bonus;_properties.MeleeSkill+=bonus;_properties.RangedSkill+=bonus;_properties.MeleeDefense+=bonus;_properties.RangedDefense+=bonus;_properties.DamageTotalMult*=1.0+bonus*0.01;}
	function onTargetHit(_skill,_target,_bodyPart,_damageHP,_damageArmor){if(_skill==null||!_skill.isAttack()||_target==null)return;local owner=this.getContainer().getActor();foreach(mark in _target.getSkills().m.Skills)if(mark!=null&&!mark.isGarbage()&&mark.getID()=="effects.bh_winner_takes_all_mark"&&mark.m.OwnerID==owner.getID())return;local mark=this.new("scripts/skills/effects/bh_winner_takes_all_mark_effect");mark.setOwner(owner.getID());_target.getSkills().add(mark);::Brotherhood.logArchetypeTest("WINNER TAKES ALL",owner,"Marked "+_target.getName()+" after a hit.");}
	function resolveMarkedDeath(_victim,_killer){local owner=this.getContainer().getActor();if(_killer!=null&&_killer.getID()==owner.getID()){++this.m.Stacks;this.m.IsHidden=false;this.getContainer().update();owner.setDirty(true);::Brotherhood.logArchetypeTest("WINNER TAKES ALL",owner,"Killed marked "+_victim.getName()+"; stacks="+this.m.Stacks+".");}else if(_killer!=null&&_killer.isAlliedWith(owner)){local lost=this.m.Stacks;this.m.Stacks=0;this.m.IsHidden=true;owner.checkMorale(-1,0);this.getContainer().update();owner.setDirty(true);::Brotherhood.logArchetypeTest("WINNER TAKES ALL",owner,_killer.getName()+" stole the marked kill on "+_victim.getName()+"; lost "+lost+" stacks and triggered a negative morale check.");}}
	function onCombatStarted(){this.m.Stacks=0;this.m.IsHidden=true;}
	function onCombatFinished(){this.m.Stacks=0;this.m.IsHidden=true;this.skill.onCombatFinished();}
});
