this.perk_bh_fencing_mastery <- this.inherit("scripts/skills/skill", {
	m = { InitiativeStacks = 0, ClearAfterTurn = false },
	function create() { this.m.ID = "perk.bh_fencing_mastery"; this.m.Name = "Fencing Mastery"; this.m.Description = ::Brotherhood.getFencerTooltip(this.m.ID); this.m.Icon = "ui/perks/bh_fencing_mastery.png"; this.m.IconDisabled = "ui/perks/bh_fencing_mastery_sw.png"; this.m.Type = this.Const.SkillType.Perk; this.m.Order = this.Const.SkillOrder.Perk; this.m.IsActive = false; }
	function onUpdate( _properties ) { _properties.Initiative += this.m.InitiativeStacks * 10; }
	function onAnySkillUsed( _skill, _target, _properties ) { local a = this.getContainer().getActor(); if (_target != null && _skill.isAttack() && a.getInitiative() > _target.getInitiative()) { _properties.FatigueEffectMult *= 0.75; _properties.DamageTotalMult *= 1.10; ::Brotherhood.logFencerTest(a, "Fencing Mastery applied -25% Fatigue and +10% damage against " + _target.getName() + "."); } else if (_target != null && _skill.isAttack()) ::Brotherhood.logFencerTest(a, "Fencing Mastery attack bonus ineligible against " + _target.getName() + " due to Initiative."); }
	function onTargetHit( _skill, _target, _bodyPart, _damageInflictedHitpoints, _damageInflictedArmor ) { if (_skill.isAttack()) { ++this.m.InitiativeStacks; this.getContainer().update(); ::Brotherhood.logFencerTest(this.getContainer().getActor(), "Fencing Mastery hit stack gained; stacks=" + this.m.InitiativeStacks + ", Initiative bonus=" + (this.m.InitiativeStacks * 10) + "."); } }
	function onTurnStart() { if (this.m.ClearAfterTurn) { ::Brotherhood.logFencerTest(this.getContainer().getActor(), "Fencing Mastery stacks expired at turn start; removed " + this.m.InitiativeStacks + " stacks."); this.m.InitiativeStacks = 0; this.m.ClearAfterTurn = false; this.getContainer().update(); } }
	function onTurnEnd() { if (this.m.InitiativeStacks > 0) { this.m.ClearAfterTurn = true; ::Brotherhood.logFencerTest(this.getContainer().getActor(), "Fencing Mastery stacks marked to expire at next turn start; stacks=" + this.m.InitiativeStacks + "."); } }
});
